###
GET http://localhost:4004/odata/v4/school/Students?$filter=student_id eq '1001'


###
GET http://localhost:4004/odata/v4/school/StudentMarks?$filter=student_id eq '1001'

###
GET http://localhost:4004/odata/v4/school/StudentFees?$filter=student_id eq '1001'

###
GET http://localhost:4007/odata/v4/school/Students

###
POST http://localhost:4004/odata/v4/school/Students
Content-Type: application/json

{
    "student_id":"1004",
    "student_name":"Vetri"
}

###
PATCH http://localhost:4007/odata/v4/school/Students(student_id='2001')
Content-Type: application/json

{
    "student_name":"Pavan"
}

###
DELETE http://localhost:4007/odata/v4/school/Students(student_id='2001')


###
POST http://localhost:4004/odata/v4/school/EmployeeAttendance
Content-Type: application/json


{
    "employee_id":"emp1001",
    "todaysdate":"2024-07-25"
}



###
GET http://localhost:4004/odata/v4/school/CompleteStudentInfo(student_id='1001')